### ISSUE TITLE
Update manifest step failure in Azure Pipelines runs on Edge

### ISSUE THREAD

**Issue by mustjab** [web-platform-tests/wpt.fyi#1291]
Seeing 'Update manifest' step fail in my Edge runs (run_all_edge=true) for the past few runs. 

Filing this bug per request from @foolip. 

Latest run with failure: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14391 
Error: 
```INFO:manifest:Skipping manifest download because existing file is recent
Traceback (most recent call last):
  File "wpt", line 5, in <module>
    wpt.main()
  File "C:\Agent\_work\1\s\tools\wpt\wpt.py", line 136, in main
    rv = script(*args, **kwargs)
  File "C:\Agent\_work\1\s\tools\manifest\update.py", line 86, in run
    update_from_cli(**kwargs)
  File "C:\Agent\_work\1\s\tools\manifest\update.py", line 44, in update_from_cli
    cache_root=kwargs["cache_root"])
  File "C:\Agent\_work\1\s\tools\manifest\manifest.py", line 497, in load_and_update
    changed = manifest.update(tree)
  File "C:\Agent\_work\1\s\tools\manifest\manifest.py", line 290, in update
    assert rel_path in path_hash
AssertionError
Cmd.exe exited with code '1'.```

**Comment by Hexcles** [comment]
There have been a few changes/fixes in manifest-related code recently. Given that Edge job that's running as I'm writing this reply seems to be working fine (https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14796), I suspect it was a bug in the manifest code that has been fixed. Could you rebase and retry?

**Comment by mustjab** [comment]
Thanks! Confirmed that the issue no longer repros after a rebase.
