### ISSUE TITLE
Results processor running out of disk space

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#271]
Urgent release blocker. Investigating.

```
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vmagent/app/main.py", line 73, in decorated_func
    return func(*args, **kwargs)
  File "/home/vmagent/app/main.py", line 57, in decorated_func
    return func(*args, **kwargs)
  File "/home/vmagent/app/main.py", line 112, in task_handler
    _atomic_write(TIMESTAMP_FILE, str(time.time()))
  File "/home/vmagent/app/main.py", line 42, in _atomic_write
    temp = tempfile.NamedTemporaryFile(mode='wt', delete=False)
  File "/env/lib/python3.6/tempfile.py", line 549, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/env/lib/python3.6/tempfile.py", line 260, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/tmp/tmpzpmp_5ls'
```

**Comment by Hexcles** [comment]
Here are my findings:

1. `gsutil rsync` (the recursive upload of the sharded results) takes a long time (>1hr) to upload a test run.
2. The worker then times out. `gunicorn` tries to restart the worker forcibly, which leaves the temporary files straying on disk.

When this happens a few times, the instance eventually runs out of disk space.

To address the problem, I'm taking two approaches:

1. For problem 1, I am still not sure why some `gsutil rsync` takes longer than others, so I'm taking some preventional / experimental measures:
    a. Increase the timeout to 1.5 hours.
    b. Use multiprocessing instead of multithreading to avoid Python GIL as suggested by [this doc](https://cloud.google.com/storage/docs/gsutil/commands/rsync#options).
2. For problem 2, I am addressing the root issue of cleanup/recovery by avoiding the problem altogether: instead of implementing some tricky cleanup/recovery logic prone to race conditions, I'll increase make the timeout for `gunicorn` longer than that for AppEngine liveness checks so that when things go wrong AppEngine will restart a fresh Docker instance (instead of having `gunicorn` to restart the worker process).

**Comment by Hexcles** [comment]
I found the root cause for problem 1: the paths.

I was doing something like `gsutil rsync /tmp/directory/ gs://wptd-staging/` where `/tmp/directory` contains a single directory whose name is the SHA of the test run.

This is effectively the same as doing `gsutil rsync /tmp/directory/[SHA]/ gs://wptd-staging/[SHA]/`, however, with wildly different performance cost. `gsutil rsync` needs to generate the list of files on both source and remote sides. The previous invocation hence needs to list *all* files in the bucket which is very expensive... This also explains why `gsutil rsync` seems to get slower: we have more files in the staging bucket now.

Besides, measure 1.a wouldn't work, because the maximum timeout on AppEngine Flex is 60 minutes.
